### ISSUE TITLE
btn-light has wrong text color

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/prestashop-ui-kit#165]
**Problem**
Button element in the UI kit has wrong color in btn-light variant.

**Desired look**
**btn-light** should have dark text.

**How to reproduce**
Insert `<button type="button" class="btn btn-light">Light</button>` anywhere in BO.

**Screenshot**
![image](https://user-images.githubusercontent.com/6097524/124084806-a591cf00-da4f-11eb-8648-f4262faf8274.png)

**Comment by NeOMakinG** [comment]
@prestascott what should be the color or even the global behavior?

**Comment by prestascott** [comment]
Hello everyone,

Thank you @Hlavtox!

@NeOMakinG I agree with David but not completely, btn-light should have dark text but only for the warning and the white button so it becomes readable and accessible. 
We know that some of our components are not accessible like the primary button, but we're currently working on it!

**Comment by Hlavtox** [comment]
@NeOMakinG @prestascott Exactly as Scott said, dark color just for -warning and -light variant ;-) https://getbootstrap.com/docs/4.0/components/buttons/
