### ISSUE TITLE
Add a ColorPicker to UI Kit

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/prestashop-ui-kit#196]
After discussion with @MatShir, @PrestaShop/ux-team could you design a colorpicker ?

After that, I will work on its implementation. Thanks for advance

**Comment by Progi1984** [comment]
Hi @PrestaShop/ux-team, have you got some news ?

**Comment by ElodieOS** [comment]
Hi @Progi1984! Yes, I am in charge of this issue and it's on the way :) 
The component is being finished and I will put it here when it's okay.

**Comment by leemyongpakvn** [comment]
Using Symfony ColorType is much simpler, as I tried at https://github.com/PrestaShop/example-modules/pull/106

**Comment by leemyongpakvn** [comment]
and https://github.com/PrestaShop/blockreassurance/pull/497

**Comment by ElodieOS** [comment]
Hello @Progi1984 
Small update for the color picker. After a discussion with @MatShir, we will keep the current color picker. I have designed one for the design system, so it should be developed but not yet. To avoid possible collisions between developments, we can keep the current one. The current color picker works, it does not pose any real problem of use, even if it is true that there is more functional.

**Comment by Progi1984** [comment]
@ElodieOS You talk about the DS from the company. The community is not aware about this one. So I can close this issue or do you prefer update this one in the future ?

**Comment by ElodieOS** [comment]
Oh sorry! Yes exactly so I think it's better to close this issue yes
