### ISSUE TITLE
How do you disabled a switch button ?

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/prestashop-ui-kit#37]
You have an example on how to make it work, but if I want to disabled the (forced) choice, how can I make it work ?

**Comment by PrestaEdit** [comment]
ping @maximebiloe  maybe ?

**Comment by aleeks** [comment]
put disabled on the input doesn't work ?
I can change the value with `disabled`

![prestaedit](https://cloud.githubusercontent.com/assets/9074610/20437075/e86934c2-adb2-11e6-8471-141e54e8d87e.png)

**Comment by PrestaEdit** [comment]
I was, of course, speaking about the switch inside this UI Kit...: http://build.prestashop.com/prestashop-ui-kit/section-3.html#section-3.7 :)

I have no problem with the switch inside the HelperForm on PrestaShop 1.6 ;-)

**Comment by aleeks** [comment]
Ahah :blush: sorry!

**Comment by eternoendless** [comment]
Hi @PrestaEdit 

You probably figured it out by now, but you can find an example in our live preview: https://cdn.rawgit.com/PrestaShop/prestashop-ui-kit/master/index.html#forms
